＃此工作流程将全新安装节点依赖项，构建源代码并在不同版本的节点上运行测试
＃有关更多信息，请参见：https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

名称：企鹅读书

在：
  workflow_dispatch：
  时间表：
     - cron的：' * / 11 * * * * '
  观看：
    类型：开始

职位：
  建立：
    运行：ubuntu-latest
    如果：github.event.repository.owner.id == github.event.sender.id
    env：
        QQREAD_BODY：$ {{ secrets.QQREAD_BODY }}
        QQREAD_TIMEURL：$ {{ secrets.QQREAD_TIMEURL }}
        QQREAD_TIMEHD：$ {{ secrets.QQREAD_TIMEHD }}
        
    步骤：
      -名称：结帐
        运行：|
          git clone https://github.com/ziye12/JavaScript.git〜/ JavaScript
      -名称：使用Node.js 12.x
        用途：actions / setup-node @ v1
        与：
          节点版本：12.x
      -名称：npm install
        如果：env.QQREAD_TIMEHD
        运行：|
          cd〜/ JavaScript
          npm安装
      -名称：'运行【企鹅读书】'
        如果：env.QQREAD_TIMEHD
        运行：|
          cd〜/ JavaScript
          节点Task / qqreads.js
        env：
          
          PUSH_KEY：$ {{ secrets.PUSH_KEY }}
          BARK_PUSH：$ {{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN：$ {{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID：$ {{ secrets.TG_USER_ID }}
          BARK_SOUND：$ {{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN：$ {{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET：$ {{ secrets.DD_BOT_SECRET }}
